services:
  app:
    container_name: app
    build:
      context: ..
      dockerfile: src/Dockerfile
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    env_file:
      - .env
    working_dir: /app
    # --http 2 - in production
    command: ["sh", "-c", "alembic upgrade head && granian main:app --host 0.0.0.0 --port 8000 --interface asgi --http auto --no-ws"]

  db:
    container_name: db
    image: postgres:17.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=$POSTGRESQL_USER
      - POSTGRES_PASSWORD=$POSTGRESQL_PASSWORD
      - POSTGRES_DB=$POSTGRESQL_NAME
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7.4.3-alpine
    restart: always
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
